name: Publish to TestPyPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          version: "0.6.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version-file: ".python-version"

      - name: "Build the package"
        run: uv build

      - name: "Upload artifacts"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: built-package
          path: dist/

  publish-to-testpypi:
    name: Upload release to TestPyPI
    needs: build
    # environment:
    #   name: testpypi
    #   url: https://test.pypi.org/p/lyricsgenius
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: ls -lR
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - run: ls -lR
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          version: "0.6.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - run: ls -lR
      - name: Download all the dists
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v.4.2.1
        with:
          name: built-package
          path: dist/

      - run: ls -lR
      - name: Publish package distributions to TestPyPI
        run: uv publish -v --publish-url https://test.pypi.org/legacy/ --trusted-publishing always dist/*
        # uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        # with:
        #   repository-url: https://test.pypi.org/legacy/
        #   verbose: true
        #   skip-existing: true
      - run: ls -lR
